{% set version = "0.7.12" %}

package:
  name: opencensus
  version: {{ version }}

source:
  url: https://github.com/census-instrumentation/opencensus-python/archive/v{{ version }}.zip
  sha256: 5398146f03de64588f95b762bc198c3bb986a732e77ddef83c10b38474ee633b

build:
  noarch: python
  number: 0
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - python
    - pip
  run:
    - python
    - opencensus-context ==0.1.2
    - google-api-core >=1.0.0, <2.0.0

test:
  imports:
    - opencensus

about:
  home: https://github.com/census-instrumentation/opencensus-python
  license: Apache-2.0
  license_file: LICENSE
  summary: OpenCensus - A stats collection and distributed tracing framework
  description: |
    OpenCensus makes getting critical telemetry out of your services easy and seamless.
    OpenCensus currently provides libraries for a number of languages that allow you to capture,
    manipulate, and export metrics and distributed traces to the backend(s) of your choice.
    OpenCensus works great with all software systems, from client applications, large monoliths,
    or highly-distributed microservices.
    OpenCensus started at Google but is now developed by a broad community of service
    developers, cloud vendors, and community contributors.
    OpenCensus isn’t tied to any particular vendor’s backend or analysis system.
    This is OpenCensus for Python.
  doc_url: https://opencensus.io/quickstart/python/
  dev_url: https://github.com/census-instrumentation/opencensus-python

extra:
  recipe-maintainers:
    - basnijholt
